replicaCount: 1

image:
  repository: abesharphpe/aie-nextjs-helloworld
  pullPolicy: Always
  tag: "latest"

 
postgresql:
  enabled: true
  auth:
    username: myuser
    password: mypass
    database: mydb

serviceAccount:
  create: true
  automount: true

autoscaling:
  enabled: false

service:
  type: ClusterIP
  port: 3000

livenessProbe:
  httpGet:
    path: /
    port: 3000
readinessProbe:
  httpGet:
    path: /
    port: 3000

kind:
  domainName: "${DOMAIN_NAME}"

  virtualService:
    endpoint: "njs-example.kind"
    istioGateway: "istio-system/litellm-gateway"
